[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "pip install -r requirements-ls1a.txt || true",
  "pip install -r requirements-browser.txt || true"
]

[start]
cmd = "bash start.sh"

